blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/scrapelesshq/scrapeless-releases/discussions/categories/feature-requests
    about: "Suggest new features or enhancements for Scrapeless"
  - name: Forums - Q&A
    url: https://github.com/scrapelesshq/scrapeless-releases/discussions/categories/forums-q-a
    about: "Ask questions or engage in general discussions about Scrapeless"